### PR TITLE
GH #72: Don't hardcode bikes_allowed for County Connection

### PR DESCRIPTION
**Pull request by rsarathy**

### CODE REVIEW

**Comment by graue** [comment]
What's your plan to either transform the GTFS feed or fix it upstream?

**Comment by rsarathy** [comment]
I don't know how to go about modifying the data in GTFS itself just yet. 

I did make one discovery, which is that presently, all County Connection routes have `bikes_allowed=1` set. This means we can remove that one piece of control flow in `Trip.java`. I'll limit this PR to that specific change.

FWIW we don't have a lot of `bikes_allowed=2` in our GTFS data. There are `159,847` routes in total, of which only `8` have `bikes_allowed=2` set.

**Comment by rsarathy** [comment]
Screenshot 2024-05-17 at 16 38 13
Multimodal trip leveraging County Connection without the hardcoding in `Trip.java`.

**Review by graue — APPROVED** [review]
Nice! Good to see County Connection no longer needs the work around.

**Pull request merged**
